dist: focal

services:
  - docker

script:
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Building Docker Images
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging Docker Images
  - docker tag udagram-api-feed mzulqarnain1/udagram-api-feed:v0
  - docker tag udagram-api-user mzulqarnain1/udagram-api-user:v0
  - docker tag udagram-frontend mzulqarnain1/udagram-frontend:v1
  - docker tag reverseproxy mzulqarnain1/reverseproxy:latest

after_success:
  - docker push mzulqarnain1/udagram-api-feed:v0
  - docker push mzulqarnain1/udagram-api-user:v0
  - docker push mzulqarnain1/udagram-frontend:v1
  - docker push mzulqarnain1/reverseproxy:latest
